googleapis/java-pubsublite

pubsublite-beam-io/pom.xml

Keep the beam artifact version in sync with the rest of pubsublite

chore: fix version region tags for next release

---

README.md

fix: Update sample code snippets in the main readme

---

pubsublite-beam-io/src/test/java/com/google/cloud/pubsublite/beam/PubsubLiteSinkTest.java

Add explicit bundling to me…ssages using TestStream.
Fixes #80  ☕️

chore: Fix flaky PubsubLiteSinkTest

---

google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/internal/wire/FlowControlBatcher.java
google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/internal/wire/SubscriberImpl.java
google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/internal/wire/TokenCounter.java
google-cloud-pubsublite/src/test/java/com/google/cloud/pubsublite/internal/wire/FlowControlBatcherTest.java
google-cloud-pubsublite/src/test/java/com/google/cloud/pubsublite/internal/wire/SubscriberImplTest.java

Fixes internal issue b/157362915.
I still need to write the tests, but this is a preview of both of the proposed approaches. I think it's not too complex.

Implements batching of flow control requests

---

google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/internal/wire/AssignerImpl.java
google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/internal/wire/PartitionAssignmentReceiver.java
google-cloud-pubsublite/src/test/java/com/google/cloud/pubsublite/internal/wire/AssignerImplTest.java
google-cloud-pubsublite/src/test/java/com/google/cloud/pubsublite/internal/wire/ConnectedAssignerImplTest.java

feat: Modify and test ConnectedAssignerImpl and AssignerImpl

---

google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/cloudpubsub/internal/AssigningSubscriber.java
google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/cloudpubsub/internal/PartitionSubscriberFactory.java
google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/internal/wire/AssignerFactory.java
google-cloud-pubsublite/src/test/java/com/google/cloud/pubsublite/cloudpubsub/internal/AssigningSubscriberTest.java

feat: Implement AssigningSubscriber which uses the PartitionAssignmentService to determine which partitions to connect to.

---

google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/cloudpubsub/internal/AssigningSubscriber.java

fix: Add missing monitor from startSubscriber.

---

google-cloud-pubsublite/src/test/java/com/google/cloud/pubsublite/cloudpubsub/internal/AssigningSubscriberTest.java
google-cloud-pubsublite/src/test/java/com/google/cloud/pubsublite/internal/wire/ConnectedAssignerImplTest.java
google-cloud-pubsublite/src/test/java/com/google/cloud/pubsublite/internal/wire/FlowControlBatcherTest.java
google-cloud-pubsublite/src/test/java/com/google/cloud/pubsublite/internal/wire/SubscriberImplTest.java

fix: Fix assorted lint errors.

---

google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/internal/wire/SingleConnection.java

fix: Update SingleConnection to not hold the monitor on upcalls

---

.readme-partials.yaml
README.md
synth.metadata

Updated `.readme-partials.yaml` with samples roughly matching those in `./samples/snippets/`. 
Then ran `python3 -m synthtool` to regenerate `README.md`. This updated `synth.metadata`.

samples: update readme samples

---

pubsublite-beam-io/README.md

docs: Update beam readme to suggest maven sources.

---

.readme-partials.yaml
samples/snippets/src/main/java/pubsublite/CreateTopicExample.java
samples/snippets/src/main/java/pubsublite/SubscriberExample.java
samples/snippets/src/test/java/pubsublite/QuickStartIT.java

Create PR after #163 is merged and published on Maven Central.

samples: update samples for automatic subscriber assignment

---

samples/snippets/src/main/java/pubsublite/UpdateSubscriptionExample.java
samples/snippets/src/main/java/pubsublite/UpdateTopicExample.java
samples/snippets/src/test/java/pubsublite/QuickStartIT.java

samples: lint 

---

google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/internal/TopicStatsClient.java
google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/internal/TopicStatsClientImpl.java
google-cloud-pubsublite/src/test/java/com/google/cloud/pubsublite/internal/TopicStatsClientImplTest.java

fix: change toString to value in TopicStatsClient

---

samples/snippets/src/test/java/pubsublite/QuickStartIT.java

samples: remove extra semicolon

---

google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/internal/ChannelCache.java
google-cloud-pubsublite/src/test/java/com/google/cloud/pubsublite/internal/ChannelCacheTest.java

Create a pool of Channels for each target.

---

google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/internal/CursorClient.java
google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/internal/CursorClientImpl.java
google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/internal/CursorClientSettings.java
google-cloud-pubsublite/src/test/java/com/google/cloud/pubsublite/internal/CursorClientImplTest.java
google-cloud-pubsublite/src/test/java/com/google/cloud/pubsublite/internal/CursorClientSettingsTest.java

This will be used by the kafka shim.

feat: Implement internal CursorClient

---

README.md
google-cloud-pubsublite/pom.xml
pubsublite-beam-io/pom.xml
samples/snapshot/pom.xml
samples/snippets/pom.xml

fix: Make flogger a runtime dependency by default.

---

.github/sync-repo-settings.yaml

chore: manage repo settings

---

google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/internal/testing/FakeApiService.java
google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/internal/testing/UnitTestExamples.java
google-cloud-pubsublite/src/test/java/com/google/cloud/pubsublite/cloudpubsub/PublisherSettingsTest.java
google-cloud-pubsublite/src/test/java/com/google/cloud/pubsublite/cloudpubsub/internal/AckSetTrackerImplTest.java
google-cloud-pubsublite/src/test/java/com/google/cloud/pubsublite/cloudpubsub/internal/AssigningSubscriberTest.java
google-cloud-pubsublite/src/test/java/com/google/cloud/pubsublite/cloudpubsub/internal/SinglePartitionSubscriberTest.java
google-cloud-pubsublite/src/test/java/com/google/cloud/pubsublite/cloudpubsub/internal/WrappingPublisherTest.java
google-cloud-pubsublite/src/test/java/com/google/cloud/pubsublite/internal/wire/RoutingPublisherTest.java
google-cloud-pubsublite/src/test/java/com/google/cloud/pubsublite/internal/wire/SinglePartitionPublisherTest.java
pubsublite-beam-io/src/test/java/com/google/cloud/pubsublite/beam/PubsubLiteSinkTest.java
pubsublite-beam-io/src/test/java/com/google/cloud/pubsublite/beam/PubsubLiteUnboundedReaderTest.java

chore: Move FakeApiService to testing folder and add UnitTestExamples

chore: Move FakeApiService to testing folder and add UnitTestExamples

---

pom.xml
pubsublite-kafka-shim/pom.xml

feat: Add pubsublite-kafka-shim directory and disable deployment

feat: Add pubsublite-kafka-shim directory and disable deployment

---

pubsublite-kafka-shim/pom.xml
pubsublite-kafka-shim/src/main/java/com/google/cloud/pubsublite/kafka/ProducerSettings.java
pubsublite-kafka-shim/src/main/java/com/google/cloud/pubsublite/kafka/PubsubLiteProducer.java
pubsublite-kafka-shim/src/test/java/com/google/cloud/pubsublite/kafka/PubsubLiteProducerTest.java

feat: Implement PubsubLiteProducer

feat: Implement PubsubLiteProducer

---

pubsublite-kafka-shim/src/main/java/com/google/cloud/pubsublite/kafka/ConsumerSettings.java
pubsublite-kafka-shim/src/main/java/com/google/cloud/pubsublite/kafka/PubsubLiteConsumer.java
pubsublite-kafka-shim/src/test/java/com/google/cloud/pubsublite/kafka/PubsubLiteConsumerTest.java

This implements Kafka's Consumer API.

feat: Implement PubsubLiteConsumer.

---

google-cloud-pubsublite/clirr-ignored-differences.xml
google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/cloudpubsub/internal/SinglePartitionSubscriber.java
google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/internal/wire/AssignerImpl.java
google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/internal/wire/BatchPublisherImpl.java
google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/internal/wire/CommitState.java
google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/internal/wire/CommitterImpl.java
google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/internal/wire/ConnectedAssignerImpl.java
google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/internal/wire/ConnectedCommitterImpl.java
google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/internal/wire/ConnectedSubscriberImpl.java
google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/internal/wire/PublisherImpl.java
google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/internal/wire/RetryingConnectionImpl.java
google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/internal/wire/RetryingConnectionObserver.java
google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/internal/wire/SingleConnection.java
google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/internal/wire/Subscriber.java
google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/internal/wire/SubscriberImpl.java
google-cloud-pubsublite/src/test/java/com/google/cloud/pubsublite/internal/wire/CommitStateTest.java
google-cloud-pubsublite/src/test/java/com/google/cloud/pubsublite/internal/wire/CommitterImplTest.java
google-cloud-pubsublite/src/test/java/com/google/cloud/pubsublite/internal/wire/SubscriberImplTest.java

This is an intermediate change needed to move to ApiException/CheckedApiException.

fix: Change internals to throw StatusException instead of return Status

---

pubsublite-beam-io/src/main/java/com/google/cloud/pubsublite/beam/TopicBacklogReaderSettings.java

fix: Add generated serialization id to TopicBacklogReaderSettings

---

google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/internal/wire/PartitionCountWatcher.java
google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/internal/wire/PartitionCountWatcherImpl.java
google-cloud-pubsublite/src/test/java/com/google/cloud/pubsublite/internal/ApiExceptionMatcher.java
google-cloud-pubsublite/src/test/java/com/google/cloud/pubsublite/internal/wire/PartitionCountWatcherImplTest.java

The topic config watcher polls the topic config and calls an update handler whenever the config cahnges

feat: Implement TopicConfigWatcher

---

google-cloud-pubsublite/src/test/java/com/google/cloud/pubsublite/it/ITVPCNegativeTest.java

Now that we don't call the admin api on publisher creation, we need to start the publisher to get an error in the VPCSC test

fix: Attempt to start the publisher and publish in the  ITVPC test

---

google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/PartitionLookupUtils.java
google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/internal/BufferingPullSubscriber.java
google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/internal/ExtractStatus.java
google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/internal/wire/PartitionCountWatcherImpl.java
google-cloud-pubsublite/src/test/java/com/google/cloud/pubsublite/it/ITVPCNegativeTest.java
pubsublite-beam-io/src/main/java/com/google/cloud/pubsublite/beam/TopicBacklogReaderSettings.java

feat: ExtractStatus for ExecutionException

---

pom.xml
pubsublite-spark-sql-streaming/pom.xml

1. use auto service instead of auto service annotation in the processor. https://screenshot.googleplex.com/AZCi8QjvdQ9AdC2
2. Add relocations to resolve grpc-netty-shaded issues.

feat: Update spark connector pom.xml

---

pubsublite-spark-sql-streaming/README.md

Spark connector readme. Left few TODOs that will be resolved later.

feat: Spark connector readme

---

google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/internal/BlockingPullSubscriberImpl.java
google-cloud-pubsublite/src/test/java/com/google/cloud/pubsublite/internal/BlockingPullSubscriberImplTest.java

feat: fix bug where blockingpullsubscriber doesn't refill flowcontrol quota.

---

pubsublite-spark-sql-streaming/pom.xml

feat: Fix snapshots references so that release could auto update

---

pubsublite-spark-sql-streaming/README.md

docs: correct beta to say unreleased

---

pubsublite-beam-io/README.md

docs: Add documentation on drain support requirements

---

pubsublite-beam-io/README.md

docs: Update Readme.md to reflect not-yet-released state of beam 2.29.0

---

google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/cloudpubsub/PublisherSettings.java
google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/cloudpubsub/SubscriberSettings.java

fix: Allow setting framework tags on cloud pubsub shim.

---

pubsublite-beam-io/README.md

- version
- known issues and solutions
- explicit imports

docs: improve PubsubLiteIO readme

---

google-cloud-pubsublite/clirr-ignored-differences.xml
google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/AdminClient.java
google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/CloudRegionOrZone.java
google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/LocationPath.java
google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/ProjectLocationBuilderHelper.java
google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/ReservationName.java
google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/ReservationPath.java
google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/SubscriptionPath.java
google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/internal/AdminClientImpl.java
google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/internal/testing/UnitTestExamples.java
google-cloud-pubsublite/src/test/java/com/google/cloud/pubsublite/internal/AdminClientImplTest.java

This feature is not be supported in the backend yet. When it is, the BetaApi annotation will be removed.

feat: Add reservation support.

---

google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/internal/wire/PartitionCountWatchingPublisher.java

fix: Use correct string formatting for log message

---

google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/internal/wire/RetryingConnectionImpl.java

fix: Respect lock annotations in RetryingConnection

---

google-cloud-pubsublite/src/test/java/com/google/cloud/pubsublite/internal/wire/AssignerSettingsTest.java
google-cloud-pubsublite/src/test/java/com/google/cloud/pubsublite/internal/wire/CommitterImplTest.java
google-cloud-pubsublite/src/test/java/com/google/cloud/pubsublite/internal/wire/PartitionCountWatchingPublisherTest.java
pom.xml
pubsublite-beam-io/src/main/java/com/google/cloud/pubsublite/beam/SubscriberOptions.java

fix: Update POMs to run errorprone analyzers and fix found issues

---

pubsublite-beam-io/README.md

docs: Update readme

---

.repo-metadata.json
synth.py

~See @Neenu1995 's comment https://github.com/googleapis/java-pubsublite/pull/687#discussion_r651082779~
Discussed offline

fix: update codeowner team in repo metadata

---

.github/workflows/samples.yaml
pubsublite-beam-io/src/main/java/com/google/cloud/pubsublite/beam/OffsetByteRange.java
pubsublite-beam-io/src/main/java/com/google/cloud/pubsublite/beam/OffsetByteRangeCoder.java
pubsublite-beam-io/src/main/java/com/google/cloud/pubsublite/beam/PerSubscriptionPartitionSdf.java
pubsublite-beam-io/src/test/java/com/google/cloud/pubsublite/beam/PerSubscriptionPartitionSdfTest.java
samples/checkstyle-suppressions.xml
samples/pom.xml
samples/snapshot/pom.xml
samples/snippets/pom.xml
samples/snippets/src/main/java/pubsublite/beam/ReadMessagesExample.java
samples/snippets/src/main/java/pubsublite/beam/WriteMessagesExample.java
samples/snippets/src/test/java/pubsublite/beam/BeamReadWriteIT.java

This mostly exists so we have a CI integration test running for this I/O. It is likely we would want more and different samples for public documentation.

samples: Add reading and writing examples with beam and add IT

---

google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/internal/wire/PartitionCountWatcherImpl.java
google-cloud-pubsublite/src/test/java/com/google/cloud/pubsublite/internal/wire/PartitionCountWatcherImplTest.java

fix: Fail the partition watcher if its consumer throws an exception

---

google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/internal/BlockingPullSubscriber.java

feat: Blocking pull subscriber is AutoCloseable

---

google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/cloudpubsub/PublisherSettings.java

fix: create a hard failure when batching settings with flow control are used

---

google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/internal/ProxyService.java
google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/internal/wire/ApiServiceUtils.java
pom.xml

fix: Ensure notifyFailed is called and all services are stopped when a permanent error happens

---

google-cloud-pubsublite-bom/pom.xml
pom.xml

chore: Add google-cloud-pubsublite-bom package

---

.github/.OwlBot.yaml
README.md

chore: fix minor owlbot .yaml typo

---

samples/snippets/src/main/java/pubsublite/CreateSubscriptionExample.java
samples/snippets/src/main/java/pubsublite/CreateTopicExample.java
samples/snippets/src/main/java/pubsublite/DeleteSubscriptionExample.java
samples/snippets/src/main/java/pubsublite/DeleteTopicExample.java
samples/snippets/src/main/java/pubsublite/GetSubscriptionExample.java
samples/snippets/src/main/java/pubsublite/GetTopicExample.java
samples/snippets/src/main/java/pubsublite/ListSubscriptionsInProjectExample.java
samples/snippets/src/main/java/pubsublite/ListSubscriptionsInTopicExample.java
samples/snippets/src/main/java/pubsublite/ListTopicsExample.java
samples/snippets/src/main/java/pubsublite/PublishWithBatchSettingsExample.java
samples/snippets/src/main/java/pubsublite/PublishWithCustomAttributesExample.java
samples/snippets/src/main/java/pubsublite/PublishWithOrderingKeyExample.java
samples/snippets/src/main/java/pubsublite/PublisherExample.java
samples/snippets/src/main/java/pubsublite/SeekSubscriptionExample.java
samples/snippets/src/main/java/pubsublite/SubscriberExample.java
samples/snippets/src/main/java/pubsublite/UpdateSubscriptionExample.java
samples/snippets/src/main/java/pubsublite/UpdateTopicExample.java
samples/snippets/src/test/java/pubsublite/QuickStartIT.java

samples: update locations to regional and zonal

---

google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/ErrorCodes.java
google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/internal/wire/PublisherImpl.java
google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/internal/wire/RetryingConnectionImpl.java

Add `CANCELLED` to retryable errors. Internal reference: b/228824524.
Also improve some logging.

fix: retry Cancelled stream errors

---

pom.xml

chore: Disable errorprone in generated code

---

README.md
pom.xml

Error_prone_annotations version is defined in the shared dependencies BOM. Let's use the version.

deps: error_prone_annotations from shared deps BOM

---

pom.xml

chore: Exclude any paths with pubsublite/proto from errorprone

---

google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/internal/wire/ServiceClients.java

We already set this to MAX_VALUE

Revert "feat: ensure large message batches can be received by subscribers"

---

README.md
google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/internal/wire/SystemExecutors.java

This can cause contention issues on high-core-count machines

fix: Update SystemExecutors to only use 4 threads, always

---

README.md
google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/internal/wire/AssignerSettings.java

fix: Add the ability to set UUID in AssignerSettings

---

README.md
google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/internal/ProxyService.java
google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/internal/wire/ServiceClients.java
google-cloud-pubsublite/src/test/java/com/google/cloud/pubsublite/cloudpubsub/internal/AssigningSubscriberTest.java
google-cloud-pubsublite/src/test/java/com/google/cloud/pubsublite/internal/wire/PublisherImplTest.java

Also change service clients to use an isolated executor.
Also change channel pools to not use a fixed pool size, and use an auto-scaling channel pool.

fix: Change proxy service to call child start methods on executors

---

README.md
google-cloud-pubsublite/clirr-ignored-differences.xml
google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/internal/AlarmFactory.java
google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/internal/wire/PublisherImpl.java

fix: Change PublisherImpl::flush to run on an unbounded executor

---

README.md
google-cloud-pubsublite/pom.xml

chore: remove temp exclusion

---

.github/workflows/unmanaged_dependency_check.yaml
README.md

b/320677251 and go/cloud-sdk-java-dependency-governance-design which Hannah reviewed the idea.

ci: unmanaged dependencies check

---

.github/sync-repo-settings.yaml

ci: remove Kokoro sample from required checks

---

.github/workflows/unmanaged_dependency_check.yaml

In this PR:
- Restore setup-java step

chore: change unmanaged dependency steps

---

.github/sync-repo-settings.yaml
README.md

[context](https://docs.google.com/document/d/1wrpyBtphdenM3BNelcnpBKGADYrGJUo686HXvSA0h-0/edit?pli=1&tab=t.0#heading=h.edczfses6zjv)

chore: make the owlbot postprocessor check non-required
