samples/install-without-bom/pom.xml, samples/snippets/pom.xml
Use `` in `samples/install-without-bom`, and `samples/snippets` (for now, to be removed later).
Use `` in `samples/snapshot`. 
---
Kokoro - Test: Java 11 and Kokoro - Test: Java 8 are flaky. Kokoro - CI seems stuck Other libraries have migrated to using GitHub actions for these.
=> fix: use right x-version-update in POM files

.github/workflows/ci.yaml, .gitignore, .kokoro/build.bat, CONTRIBUTING.md, samples/snippets/src/main/java/pubsublite/DeleteTopicExample.java, synth.metadata, synth.py
Common template updates:
* shared contributing guide
* adds GitHub actions ci configuration
Fixes #59
=> chore: fix sample snippet tag to fix synth and update common templates

google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/internal/wire/SubscriberImpl.java, google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/internal/wire/TokenCounter.java, google-cloud-pubsublite/src/test/java/com/google/cloud/pubsublite/internal/wire/SubscriberImplTest.java
If a seek is inFlight and a stream is retried, retrying the inFlight seek.
If an internal seek is in flight, and a client initiates a seek, block until the internal seek completes.
=> fix: keep track of internal seek

google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/internal/wire/CommitterImpl.java, google-cloud-pubsublite/src/test/java/com/google/cloud/pubsublite/internal/wire/CommitterImplTest.java
This avoids waiting on its own actions to complete if one of the commit futures returned by abort() calls stopAsync on the committer.
=> fix: Modify CommitterImpl to exit early in case of permanent failure

samples/snapshot/pom.xml, samples/snippets/pom.xml
Manually update library versions in snippets and snapshot pom because Renovate Bot isn't updating them. 
Autosynth should trigger README update today or tomorrow.
=> samples: update lib version

samples/snippets/src/main/java/pubsublite/CreateSubscriptionExample.java, samples/snippets/src/main/java/pubsublite/CreateTopicExample.java, samples/snippets/src/main/java/pubsublite/DeleteSubscriptionExample.java, samples/snippets/src/main/java/pubsublite/DeleteTopicExample.java, samples/snippets/src/main/java/pubsublite/GetSubscriptionExample.java, samples/snippets/src/main/java/pubsublite/GetTopicExample.java, samples/snippets/src/main/java/pubsublite/ListSubscriptionsInProjectExample.java, samples/snippets/src/main/java/pubsublite/ListSubscriptionsInTopicExample.java, samples/snippets/src/main/java/pubsublite/ListTopicsExample.java, samples/snippets/src/main/java/pubsublite/PublishWithBatchSettingsExample.java, samples/snippets/src/main/java/pubsublite/PublishWithCustomAttributesExample.java, samples/snippets/src/main/java/pubsublite/PublishWithOrderingKeyExample.java, samples/snippets/src/main/java/pubsublite/PublisherExample.java, samples/snippets/src/main/java/pubsublite/SubscriberExample.java, samples/snippets/src/main/java/pubsublite/UpdateSubscriptionExample.java, samples/snippets/src/main/java/pubsublite/UpdateTopicExample.java, samples/snippets/src/test/java/pubsublite/QuickStartIT.java
Add 3 post-Public Preview publish samples for the Pub/Sub Lite publish [docs](https://cloud.google.com/pubsub/lite/docs/publishing) (currently have links to Java documentation as placeholders):
Internal b/157257388: publish with ordering key
Internal b/154738648: publish messages with custom attributes
Internal b/154738314: publish with batch settings
Also made some formatting changes to existing samples.
=> samples: add post-preview samples and reformat

google-cloud-pubsublite/src/test/java/com/google/cloud/pubsublite/it/ITVPCNegativeTest.java
Add integration tests to verify successful rejection of service when a project is being used outside its VPC perimeter.
These tests are **NOT** run automatically and require the env variable `GOOGLE_CLOUD_TESTS_IN_VPCSC=true` to be set. Additionally, the project to run the tests against can be set with env variable `GOOGLE_CLOUD_TESTS_VPCSC_OUTSIDE_PERIMETER_PROJECT_NUMBER`.
A simple way to run these tests is as follows:
```bash
export GOOGLE_APPLICATION_CREDENTIALS=/path/to/service/account.json
export GOOGLE_CLOUD_TESTS_IN_VPCSC=true
export GOOGLE_CLOUD_TESTS_VPCSC_OUTSIDE_PERIMETER_PROJECT_NUMBER=<project-number>
mvn clean -Dtest=ITVPCNegativeTest -DfailIfNoTests=false test
```
Internal b/159125512.
=> test: Add VPC-SC Negative Integration Tests

google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/AdminClientSettings.java, google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/Constants.java, google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/internal/AdminClientImpl.java, google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/internal/RetryingExecutorUtil.java, google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/internal/TopicStatsClient.java, google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/internal/TopicStatsClientImpl.java, google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/internal/TopicStatsClientSettings.java, google-cloud-pubsublite/src/test/java/com/google/cloud/pubsublite/internal/AdminClientImplTest.java, google-cloud-pubsublite/src/test/java/com/google/cloud/pubsublite/internal/TestUtil.java, google-cloud-pubsublite/src/test/java/com/google/cloud/pubsublite/internal/TopicStatsClientImplTest.java
Adds an interface and implementation for the TopicStatsClient. I've kept
them both in internal for now since we don't yet expose an API for
interacting with the CursorService.
=> feat: Add the TopicStats client

.readme-partials.yaml, samples/snippets/src/main/java/pubsublite/CreateTopicExample.java, samples/snippets/src/main/java/pubsublite/SubscriberExample.java, samples/snippets/src/test/java/pubsublite/QuickStartIT.java
Reverts googleapis/java-pubsublite#189
I should have merged it after release version in samples/snippets/pom.xml is updated by autosynth.
=> Revert "samples: update samples for automatic subscriber assignment"

synth.metadata
Ran:
```bash
SYNTHTOOL_TRACK_OBSOLETE_FILES=true python3 -m synthtool
```
=> chore: fix synth.metadata file list

pubsublite-beam-io/src/main/java/com/google/cloud/pubsublite/beam/TopicBacklogReader.java, pubsublite-beam-io/src/main/java/com/google/cloud/pubsublite/beam/TopicBacklogReaderImpl.java, pubsublite-beam-io/src/test/java/com/google/cloud/pubsublite/beam/TopicBacklogReaderImplTest.java
This class allows users to provide a partition -> start cursor mapping,
and aggregates the message statistics over multiple partitions.
=> feat: Add the TopicBacklogReader

pubsublite-beam-io/pom.xml, pubsublite-beam-io/src/main/java/com/google/cloud/pubsublite/beam/PubsubLiteUnboundedReader.java, pubsublite-beam-io/src/main/java/com/google/cloud/pubsublite/beam/PubsubLiteUnboundedSource.java, pubsublite-beam-io/src/main/java/com/google/cloud/pubsublite/beam/SubscriberOptions.java, pubsublite-beam-io/src/test/java/com/google/cloud/pubsublite/beam/PubsubLiteUnboundedReaderTest.java
We use the TopicStatsService to compute the backlog size for the
assigned splits in the PubsubLiteUnbounded Reader.
We will refresh backlog information every ten seconds, and will use
stale information for up to a minute if the topic stats serivce is
unavailable.
Constructing the TopicBacklogReader in SubscriberOptions is a bit
awkward, but I wanted to make sure we don't need to re-resolve the
subscription -> topic mapping when we split or merge the source.
Otherwise we end up with a hard dependency on the admin service.
=> feat: Use TopicStats to implement getSplitBacklog

google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/internal/BufferingPullSubscriber.java, google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/internal/PullSubscriber.java, google-cloud-pubsublite/src/test/java/com/google/cloud/pubsublite/internal/BufferingPullSubscriberTest.java, pubsublite-beam-io/src/main/java/com/google/cloud/pubsublite/beam/PubsubLiteUnboundedReader.java, pubsublite-beam-io/src/main/java/com/google/cloud/pubsublite/beam/PubsubLiteUnboundedSource.java, pubsublite-beam-io/src/main/java/com/google/cloud/pubsublite/beam/SubscriberOptions.java, pubsublite-beam-io/src/test/java/com/google/cloud/pubsublite/beam/PubsubLiteUnboundedReaderTest.java
This enables it to be reused outside of the beam library.
=> chore: Move BufferingPullSubscriber into google-cloud-pubsublite

google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/internal/BufferingPullSubscriber.java, google-cloud-pubsublite/src/test/java/com/google/cloud/pubsublite/internal/BufferingPullSubscriberTest.java, pubsublite-beam-io/src/main/java/com/google/cloud/pubsublite/beam/PubsubLiteUnboundedSource.java
Seeking after sending tokens will discard any flow control tokens sent to the server. Also, update BufferingPullSubscriber to accept arbitrary initial seek requests.
=> fix: Fix BufferingPullSubscriber to not seek after sending flow control tokens.

pubsublite-kafka-shim/pom.xml, pubsublite-kafka-shim/src/main/java/com/google/cloud/pubsublite/kafka/SingleSubscriptionConsumerImpl.java, pubsublite-kafka-shim/src/test/java/com/google/cloud/pubsublite/kafka/SingleSubscriptionConsumerImplTest.java
This is an API that can be used to implement the kafka Consumer API.
=> feat: Implement SingleSubscriptionConsumerImpl

google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/cloudpubsub/PublisherSettings.java, google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/cloudpubsub/SubscriberSettings.java, google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/internal/wire/RetryingConnectionImpl.java, google-cloud-pubsublite/src/test/java/com/google/cloud/pubsublite/internal/wire/AssignerImplTest.java, google-cloud-pubsublite/src/test/java/com/google/cloud/pubsublite/internal/wire/CommitterImplTest.java, google-cloud-pubsublite/src/test/java/com/google/cloud/pubsublite/internal/wire/PublisherImplTest.java, google-cloud-pubsublite/src/test/java/com/google/cloud/pubsublite/internal/wire/RetryingConnectionHelpers.java, google-cloud-pubsublite/src/test/java/com/google/cloud/pubsublite/internal/wire/SubscriberImplTest.java
This lets publishers initialize many connections at once for lower startup times with many partitions.
=> fix: Make connections start up asynchronously

pubsublite-kafka-shim/src/main/java/com/google/cloud/pubsublite/kafka/ConsumerSettings.java, pubsublite-kafka-shim/src/main/java/com/google/cloud/pubsublite/kafka/ProducerSettings.java, pubsublite-kafka-shim/src/main/java/com/google/cloud/pubsublite/kafka/PubsubLiteConsumer.java, pubsublite-kafka-shim/src/main/java/com/google/cloud/pubsublite/kafka/PubsubLiteProducer.java, pubsublite-kafka-shim/src/main/java/com/google/cloud/pubsublite/kafka/SharedBehavior.java, pubsublite-kafka-shim/src/test/java/com/google/cloud/pubsublite/kafka/PubsubLiteConsumerTest.java, pubsublite-kafka-shim/src/test/java/com/google/cloud/pubsublite/kafka/PubsubLiteProducerTest.java, pubsublite-kafka-shim/src/test/java/com/google/cloud/pubsublite/kafka/SharedBehaviorTest.java
…instead of looking it up.
This prevents making too many queries to the number of partitions.
=> fix: Change Kafka{Producer/Consumer} to fix the number of partitions

samples/snippets/src/main/java/pubsublite/CreateSubscriptionExample.java, samples/snippets/src/main/java/pubsublite/CreateTopicExample.java, samples/snippets/src/main/java/pubsublite/UpdateSubscriptionExample.java
1. Update create topic sample to use `capacity` in place of `scale` because it's deprecated. 
https://github.com/googleapis/java-pubsublite/blob/d26cbcf29262bb3123cc5afe360f48a63a80aa42/proto-google-cloud-pubsublite-v1/src/main/proto/google/cloud/pubsublite/v1/common.proto#L100-L108
1. Update comments for delivery requirement.
=> samples: update create topic sample and comments

google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/internal/DefaultRoutingPolicy.java, google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/internal/RoutingPolicy.java, google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/internal/testing/FakeApiService.java, google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/internal/wire/PartitionCountWatchingPublisher.java, google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/internal/wire/PartitionCountWatchingPublisherSettings.java, google-cloud-pubsublite/src/test/java/com/google/cloud/pubsublite/internal/wire/PartitionCountWatchingPublisherTest.java
This publisher watches the partition count and adds partitions when the topic's partition count increases.
=> feat: Add the PartitionCountWatchingPublisher

google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/internal/Lazy.java, google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/internal/ServiceClients.java, google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/internal/wire/RetryingConnectionImpl.java
Also use a shared executor for all GRPC clients to reduce total threadcount and fix errors when tearing down executors used by GRPC connections.
Also add logging to RetryingConnectionImpl
Also ensure all calls out from RetryingConnectionImpl cannot leak exceptions.
Also ensure all streams have heartbeating enabled.
=> fix: Deadlock in RetryingConnectionImpl when tearing down a connection

google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/AdminClientSettings.java, google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/internal/CursorClientSettings.java, google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/internal/TopicStatsClientSettings.java, google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/internal/wire/AssignerBuilder.java, google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/internal/wire/CommitterBuilder.java, google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/internal/wire/PublisherBuilder.java, google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/internal/wire/RoutingMetadata.java, google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/internal/wire/ServiceClients.java, google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/internal/wire/SubscriberBuilder.java, google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/internal/wire/SubscriberFactory.java, pubsublite-spark-sql-streaming/src/main/java/com/google/cloud/pubsublite/spark/PartitionSubscriberFactory.java, pubsublite-spark-sql-streaming/src/main/java/com/google/cloud/pubsublite/spark/PslContinuousInputPartition.java, pubsublite-spark-sql-streaming/src/main/java/com/google/cloud/pubsublite/spark/PslContinuousReader.java, pubsublite-spark-sql-streaming/src/main/java/com/google/cloud/pubsublite/spark/PslDataSource.java, pubsublite-spark-sql-streaming/src/main/java/com/google/cloud/pubsublite/spark/PslDataSourceOptions.java, pubsublite-spark-sql-streaming/src/main/java/com/google/cloud/pubsublite/spark/PslMicroBatchReader.java, pubsublite-spark-sql-streaming/src/test/java/com/google/cloud/pubsublite/spark/PslContinuousReaderTest.java, pubsublite-spark-sql-streaming/src/test/java/com/google/cloud/pubsublite/spark/PslMicroBatchReaderTest.java
=> feat: Add non google default creds provider to subscribers in Spark Connector

google-cloud-pubsublite/clirr-ignored-differences.xml, google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/Constants.java, google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/internal/wire/PublisherImpl.java
There still exists a 3.5MiB byte limit server side, and a protocol level 4MiB message limit.
=> fix: Remove per-message byte limit in client

pubsublite-spark-sql-streaming/examples/simple_read.py, pubsublite-spark-sql-streaming/src/main/java/com/google/cloud/pubsublite/spark/PslContinuousReader.java, pubsublite-spark-sql-streaming/src/main/java/com/google/cloud/pubsublite/spark/PslMicroBatchInputPartition.java, pubsublite-spark-sql-streaming/src/main/java/com/google/cloud/pubsublite/spark/PslMicroBatchReader.java
This adds a simple read example and fixes the following bugs:
1. microbatchinputpartition subscriber should initially seek to startoffset instead of endoffset
2. lambda introduced in previous PRs brings `this`(PslXXXReader) as part of serialization, this PR detached `this` in lambda.
=> feat: Adds examples and fixes bugs in spark connector

pubsublite-spark-sql-streaming/src/main/java/com/google/cloud/pubsublite/spark/PslContinuousInputPartition.java, pubsublite-spark-sql-streaming/src/main/java/com/google/cloud/pubsublite/spark/PslContinuousInputPartitionReader.java, pubsublite-spark-sql-streaming/src/main/java/com/google/cloud/pubsublite/spark/PslContinuousReader.java, pubsublite-spark-sql-streaming/src/main/java/com/google/cloud/pubsublite/spark/PslMicroBatchInputPartitionReader.java, pubsublite-spark-sql-streaming/src/main/java/com/google/cloud/pubsublite/spark/PslMicroBatchReader.java, pubsublite-spark-sql-streaming/src/main/java/com/google/cloud/pubsublite/spark/PslSparkUtils.java, pubsublite-spark-sql-streaming/src/main/java/com/google/cloud/pubsublite/spark/SparkSourceOffset.java, pubsublite-spark-sql-streaming/src/test/java/com/google/cloud/pubsublite/spark/SparkSourceOffsetTest.java
=> feat: Changed assert to Preconditions check

google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/Constants.java, google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/internal/wire/PublisherImpl.java, google-cloud-pubsublite/src/test/java/com/google/cloud/pubsublite/internal/wire/PublisherImplTest.java
This prevents publishers which are network isolated for a while from appearing disconnected when the server attempts to acknowledge messages.
=> fix: Rebatch messages when restarting a publish stream

pubsublite-beam-io/pom.xml
Fixes the releases for pubsublite-beam-io artifact moving forward.
The artifact's pom.xml was missing the version replace tag so when we tried to release 0.11.0, this artifact still had 0.10.1-SNAPSHOT and couldn't be released.
=> build: fix version replacement in pubsublite-beam-io

synth.metadata
Remove handwritten file Constants.java from the list of generated files in synth.metadata to stop autosynth from suggesting PRs which delete Constants.java file
=> chore: remove Constants.java from the list of generated files in synth.metadata

pubsublite-beam-io/src/main/java/com/google/cloud/pubsublite/beam/SubscribeTransform.java, pubsublite-beam-io/src/main/java/com/google/cloud/pubsublite/beam/SubscriberOptions.java, pubsublite-beam-io/src/main/java/com/google/cloud/pubsublite/beam/Uuid.java
- UUIDs generated randomly are not valid UTF-8 strings so they cannot be read from the CPS shim by default
- Restrictions on bundle closing make it hard to test PSL with windowing pipelines
Fixes #542 ☕️
=> fix: Two QOL issues with PubsubLiteIO

pubsublite-beam-io/src/main/java/com/google/cloud/pubsublite/beam/Publishers.java
Writing to a Lite topic will work with this fix.
But a pipeline that writes a bounded source to a Lite topic doesn't exit.
=> fix: Set batching settings on SinglePartitionPublisher

google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/internal/wire/PartitionCountWatcherImpl.java, google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/internal/wire/PublisherImpl.java, google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/internal/wire/RetryingConnectionImpl.java, google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/internal/wire/ServiceClients.java, google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/internal/wire/SubscriberImpl.java, google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/internal/wire/SystemExecutors.java, pubsublite-beam-io/src/main/java/com/google/cloud/pubsublite/beam/PerServerPublisherCache.java, pubsublite-beam-io/src/main/java/com/google/cloud/pubsublite/beam/PublisherCache.java, pubsublite-beam-io/src/main/java/com/google/cloud/pubsublite/beam/Publishers.java, pubsublite-beam-io/src/main/java/com/google/cloud/pubsublite/beam/PubsubLiteSink.java
Also prevent creation of per-object thread pools which are largely unused and may prevent shutdown if not using daemon threads.
=> fix: Centralize alarm executor creation for Pub/Sub Lite

google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/internal/TopicStatsClient.java, google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/internal/TopicStatsClientImpl.java, google-cloud-pubsublite/src/test/java/com/google/cloud/pubsublite/internal/TopicStatsClientImplTest.java
Adds methods to the internal TopicStatsClient for computing cursors for publish or event timestamps.
=> feat: Compute cursors for publish and event timestamps

.github/sync-repo-settings.yaml
Members in https://github.com/orgs/googleapis/teams/api-pubsublite are admins of the repo now. 
This GitHub Team Sync team is mapped to the internal Lite Dev team.
=> chore: allow lite team members to manage the repo

google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/cloudpubsub/SubscriberSettings.java, google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/cloudpubsub/internal/AckSetTracker.java, google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/cloudpubsub/internal/AckSetTrackerImpl.java, google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/cloudpubsub/internal/ResettableSubscriberFactory.java, google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/cloudpubsub/internal/SinglePartitionSubscriber.java, google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/internal/wire/ApiExceptionCommitter.java, google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/internal/wire/CommitState.java, google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/internal/wire/Committer.java, google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/internal/wire/CommitterImpl.java, google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/internal/wire/NextOffsetTracker.java, google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/internal/wire/SubscriberBuilder.java, google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/internal/wire/SubscriberImpl.java, google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/internal/wire/SubscriberResetHandler.java, google-cloud-pubsublite/src/test/java/com/google/cloud/pubsublite/cloudpubsub/internal/AckSetTrackerImplTest.java, google-cloud-pubsublite/src/test/java/com/google/cloud/pubsublite/cloudpubsub/internal/SinglePartitionSubscriberTest.java, google-cloud-pubsublite/src/test/java/com/google/cloud/pubsublite/internal/wire/CommitStateTest.java, google-cloud-pubsublite/src/test/java/com/google/cloud/pubsublite/internal/wire/CommitterImplTest.java, google-cloud-pubsublite/src/test/java/com/google/cloud/pubsublite/internal/wire/SubscriberBuilderTest.java, google-cloud-pubsublite/src/test/java/com/google/cloud/pubsublite/internal/wire/SubscriberImplTest.java
Prepares for handling the `RESET` signal from the server, by:
* Discarding outstanding acks for delivered messages.
* Waiting for the committer to flush pending commits and receive the acknowledgment from the server.
* Then resetting subscriber state, including canceling any in-flight client seeks.
Notes:
* This PR is effectively a no-op as `SinglePartitionSubscriber.onSubscriberReset` returns false for now.
* The next PR will fully handle admin seeks by setting InitialSubscribeRequest.initial_location and implement `SinglePartitionSubscriber.onSubscriberReset`. Omitted to keep the size of the PR down.
* `CommitState.complete` had to be refactored to just throw (and not abort) because `CommitterImpl.waitUntilEmpty` should throw when there are excess commit responses, since the committer …
=> feat: Ability to reset subscriber upon out of band seek

google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/internal/wire/PartitionCountWatchingPublisher.java, pubsublite-beam-io/src/main/java/com/google/cloud/pubsublite/beam/SubscribeTransform.java, pubsublite-beam-io/src/main/java/com/google/cloud/pubsublite/beam/SubscriberOptions.java, pubsublite-beam-io/src/main/java/com/google/cloud/pubsublite/beam/SubscriptionPartitionLoader.java
Explicit partitions can always be added back, but this reduces the public API surface unless they're needed.
https://issues.apache.org/jira/browse/BEAM-12459 opened to prevent the need for the watch workaround.
=> fix: Remove explicit partitions which are not particularly useful and add Watch workaround.

google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/internal/wire/ConnectedSubscriberImpl.java, pubsublite-beam-io/src/main/java/com/google/cloud/pubsublite/beam/OffsetByteRange.java, pubsublite-beam-io/src/main/java/com/google/cloud/pubsublite/beam/OffsetByteRangeTracker.java, pubsublite-beam-io/src/main/java/com/google/cloud/pubsublite/beam/PerSubscriptionPartitionSdf.java, pubsublite-beam-io/src/main/java/com/google/cloud/pubsublite/beam/SubscribeTransform.java, pubsublite-beam-io/src/main/java/com/google/cloud/pubsublite/beam/SubscriptionPartitionProcessorImpl.java, pubsublite-beam-io/src/main/java/com/google/cloud/pubsublite/beam/TrackerWithProgress.java, pubsublite-beam-io/src/test/java/com/google/cloud/pubsublite/beam/OffsetByteRangeTrackerTest.java, pubsublite-beam-io/src/test/java/com/google/cloud/pubsublite/beam/PerSubscriptionPartitionSdfTest.java, pubsublite-beam-io/src/test/java/com/google/cloud/pubsublite/beam/SubscriptionPartitionProcessorImplTest.java
=> feat: Change restriction to OffsetByteRange to allow functioning with runnerv2.

.github/sync-repo-settings.yaml
Now that we are adding sample tests (https://github.com/googleapis/java-pubsublite/pull/686) as a way to test the beam module of java-pubsublite. Requiring sample tests to pass in presubmit will help catch any bugs before committing to master.
=> chore: require sample tests to pass in presubmit

pubsublite-beam-io/src/main/java/com/google/cloud/pubsublite/beam/ManagedBacklogReaderFactory.java, pubsublite-beam-io/src/main/java/com/google/cloud/pubsublite/beam/ManagedBacklogReaderFactoryImpl.java, pubsublite-beam-io/src/main/java/com/google/cloud/pubsublite/beam/OffsetByteRangeTracker.java, pubsublite-beam-io/src/main/java/com/google/cloud/pubsublite/beam/PerSubscriptionPartitionSdf.java, pubsublite-beam-io/src/main/java/com/google/cloud/pubsublite/beam/SubscribeTransform.java, pubsublite-beam-io/src/test/java/com/google/cloud/pubsublite/beam/OffsetByteRangeTrackerTest.java, pubsublite-beam-io/src/test/java/com/google/cloud/pubsublite/beam/PerSubscriptionPartitionSdfTest.java
ManagedChannel emits a warning when it is marked for finalization; calling close() in the finalize() method is insufficient to remove this warning. Add ManagedBacklogReaderFactory to tie ManagedChannel shutdown to the SDF finalize method
Fixes #548 ☕️
=> fix: ManagedChannel shutdown issues

synth.py
Prevent synthtool-proposed changes in checkstyle tests, as in this PR https://github.com/googleapis/java-pubsublite/pull/706/files
```yaml
- name: Run checkstyle
run: mvn -P lint --quiet --batch-mode checkstyle:check
working-directory: samples/snippets
```
The working directory should stay as `samples`. We recently added https://github.com/googleapis/java-pubsublite/blob/master/samples/checkstyle-suppressions.xml in #686 and it requires we run checkstyel from `samples/` instead of `sampels/snippets`.
=> chore: prevent synthtool from changing samples.yaml

pubsublite-beam-io/src/main/java/com/google/cloud/pubsublite/beam/PubsubLiteIO.java
This will enable creating a POC for aliasing it in the beam repo.
This class has no instance methods, just static ones.
=> fix: Make PubsubLiteIO not final and have protected constructor

google-cloud-pubsublite/clirr-ignored-differences.xml, google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/PartitionLookupUtils.java, google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/SubscriptionPath.java, google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/TopicPath.java, google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/cloudpubsub/PublisherSettings.java, google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/cloudpubsub/SubscriberSettings.java, pubsublite-beam-io/src/main/java/com/google/cloud/pubsublite/beam/Publishers.java, pubsublite-beam-io/src/main/java/com/google/cloud/pubsublite/beam/SubscribeTransform.java, pubsublite-beam-io/src/main/java/com/google/cloud/pubsublite/beam/SubscriberOptions.java, pubsublite-beam-io/src/main/java/com/google/cloud/pubsublite/beam/TopicBacklogReaderSettings.java
=> fix: Make the one breaking change required to allow regions on TopicPath or SubscriptionPath

.github/workflows/samples.yaml, samples/snippets/pom.xml
This is a region tag misuse. The Beam deps aren't needed for the Lite Java quickstart.
https://cloud.google.com/pubsub/lite/docs/quickstart#pubsublite-client-libraries-java
=> samples: exclude beam deps from pubsublite samples POM

google-cloud-pubsublite/clirr-ignored-differences.xml, google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/AdminClient.java, google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/BacklogLocation.java, google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/internal/AdminClientImpl.java, google-cloud-pubsublite/src/test/java/com/google/cloud/pubsublite/internal/AdminClientImplTest.java
Allows `BacklogLocation` to be referenced from an upcoming class containing seek targets.
=> fix: Move BacklogLocation enum to standalone file

google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/internal/wire/AssignerImpl.java, google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/internal/wire/PublisherImpl.java, google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/internal/wire/RetryingConnectionImpl.java
* Log the partitions that a subscriber is assigned, at Info.
* Log verbose messages around stream reconnection (for prober debugging).
=> refactor: Add debug logging

google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/CloudRegionOrZone.java, google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/internal/wire/ConnectedSubscriberImpl.java, google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/internal/wire/PartitionCountWatchingPublisher.java, google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/internal/wire/SubscriberFactory.java, google-cloud-pubsublite/src/test/java/com/google/cloud/pubsublite/internal/wire/ConnectedSubscriberImplTest.java
* Makes `CloudRegionOrZone.Kind` public so that users can check the kind before accessing region() or zone(). Otherwise an exception is thrown when accessing the wrong type.
* Fixed a few lint errors.
=> fix: Updates for import

pubsublite-beam-io/src/test/java/com/google/cloud/pubsublite/beam/SubscriptionPartitionProcessorImplTest.java
Wait for 10ms for the PartitionProcessor to fail after failing the underlying subscriber.
Fixes #767 ☕️
=> fix(test): deflake SubscriptionPartitionProcessorImplTest

samples/snippets/src/main/java/pubsublite/PublishWithCustomAttributesExample.java, samples/snippets/src/main/java/pubsublite/SubscriberExample.java
Fixes #856 
Show the proper way to publish a message to Pub/Sub Lite with an event time as an attribute.
=> samples: add event time as a custom attribute

google-cloud-pubsublite/clirr-ignored-differences.xml, google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/cloudpubsub/internal/AckSetTrackerImpl.java, google-cloud-pubsublite/src/test/java/com/google/cloud/pubsublite/cloudpubsub/internal/AckSetTrackerImplTest.java
=> fix: simplify AckSetTrackerImpl and make acks after shutdown not cause a permanent error

google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/cloudpubsub/internal/AssigningSubscriber.java, google-cloud-pubsublite/src/test/java/com/google/cloud/pubsublite/cloudpubsub/internal/AssigningSubscriberTest.java
Possible improvement/fix for #871, unclear as I've been unable to reproduce.
=> fix: catch more possible errors in AssigningSubscriber and don't have hard errors on stopping subscribers

google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/cloudpubsub/PartitionSubscriberClientSupplier.java, google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/cloudpubsub/SubscriberSettings.java, google-cloud-pubsublite/src/test/java/com/google/cloud/pubsublite/cloudpubsub/SubscriberSettingsTest.java
Passes the subscription path and partition to the supplier.
Replaces SubscriberSettings.setSubscriberServiceClientSupplier, which is deprecated.
=> chore: Add SubscriberSettings.setPartitionSubscriberClientSupplier

google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/internal/wire/ConnectedAssignerImpl.java, google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/internal/wire/SingleConnection.java, google-cloud-pubsublite/src/test/java/com/google/cloud/pubsublite/internal/wire/ConnectedAssignerImplTest.java
If the client reconnects and assignments have not changed, the server does not send an initial assignment set. This can cause subscriber shutdown to hang because the lock is held in SingleConnection while waiting for stream initialization to complete.
=> fix: Partition assignment stream does not require an initial response

README.md, google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/internal/wire/PublisherImpl.java, google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/internal/wire/SerialBatcher.java, google-cloud-pubsublite/src/test/java/com/google/cloud/pubsublite/internal/wire/SerialBatcherTest.java
This call can cause user publish() calls to block until the stream is able to reconnect on transient stream disconnections
=> fix: Change PublisherImpl and SerialBatcher interplay to not call into the network layer on the downcall

README.md, google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/internal/wire/PartitionCountWatcherImpl.java
This is a workaround for https://github.com/googleapis/gax-java/issues/1577
=> fix: Add a timeout to getTopicPartitionCount

README.md, google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/cloudpubsub/internal/WrappingPublisher.java, google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/internal/CheckedApiPreconditions.java, google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/internal/DefaultRoutingPolicy.java, google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/internal/ExtractStatus.java, google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/internal/wire/ConnectedSubscriberImpl.java, google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/internal/wire/PartitionCountWatchingPublisher.java, google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/internal/wire/PublisherImpl.java, google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/internal/wire/RoutingPublisher.java, google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/internal/wire/SinglePartitionPublisher.java
All of the uses of DirectExecutor are performing simple data-only transformations and are in the publisher hotpath
=> fix: Numerous publish path performance issues

google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/internal/wire/RetryingConnectionImpl.java
Stream initializations can sometimes be stalled, which starves tasks using the alarm executor. This performs reinitialization in an unbounded (futures) executor.
=> fix: Reinitialize streams in an unbounded executor

google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/internal/SerialExecutor.java, google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/internal/wire/SubscriberImpl.java, google-cloud-pubsublite/src/test/java/com/google/cloud/pubsublite/internal/SerialExecutorTest.java, google-cloud-pubsublite/src/test/java/com/google/cloud/pubsublite/internal/wire/SubscriberImplTest.java
The messages are ordered when they are processed by the wire subscriber. However, if the user message receiver is slow, different message batches may be concurrently processed by the receiver. The wire subscriber now serializes delivery of the message batches.
Internal: cl/423978493.
=> fix: Ensure messages are delivered in order

google-cloud-pubsublite/clirr-ignored-differences.xml, google-cloud-pubsublite/pom.xml, google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/internal/wire/ConnectedAssignerImpl.java, google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/internal/wire/ConnectedCommitterImpl.java, google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/internal/wire/RetryingConnectionImpl.java, google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/internal/wire/SingleConnection.java, google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/internal/wire/StreamIdleTimer.java, google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/internal/wire/SystemExecutors.java, google-cloud-pubsublite/src/test/java/com/google/cloud/pubsublite/internal/wire/ConnectedCommitterImplTest.java, google-cloud-pubsublite/src/test/java/com/google/cloud/pubsublite/internal/wire/StreamIdleTimerTest.java
Mitigates hanging streams by detecting idle streams and reconnecting after a timeout (default 10min for partition assignment streams, 2min for all others).
The StreamIdleTimer is restarted when the client receives a response on the stream. The stream is reinitialized when the timeout expires. For publish and commit streams, the timeout will still expire even if there is no user activity.
Internal: cl/422650400 and subsequent fixes.
=> fix: Mitigate gRPC stream connection issues

google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/cloudpubsub/SubscriberSettings.java
Close the partition subscriber factory (which contains the client stubs) last. If the Committer has a pending commit, it will try to send it before shutdown. The commit stream will repeatedly fail to reconnect with error "UNAVAILABLE: Channel shutdown invoked" and cause shutdown to hang.
Internal: b/218984062.
=> fix: Committer stuck in retry loop on shutdown

google-cloud-pubsublite/src/test/java/com/google/cloud/pubsublite/internal/wire/ConnectedCommitterImplTest.java
Allow plenty of time for the `connectionClosed` condition to occur.
Fixes: https://github.com/googleapis/java-pubsublite/issues/1042
=> test: Flaky ConnectedCommitterImplTest

google-cloud-pubsublite/clirr-ignored-differences.xml, google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/internal/ExtractStatus.java, google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/internal/wire/ResetSignal.java, google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/internal/wire/RetryingConnectionImpl.java, google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/internal/wire/SubscriberBuilder.java, google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/internal/wire/SubscriberImpl.java, google-cloud-pubsublite/src/test/java/com/google/cloud/pubsublite/internal/wire/SubscriberImplTest.java
Beam needs a way to know that a <subscription, partition> has been relocated to another worker, and provides no in-model way to do this. We can reuse the duplicate connection error to detect occurences of this and respect them.
=> feat: add explicit duplicate subscriber handling to SubscriberImpl for beam

README.md, google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/internal/SerialExecutor.java, google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/internal/wire/SubscriberImpl.java, google-cloud-pubsublite/src/test/java/com/google/cloud/pubsublite/internal/SerialExecutorTest.java, google-cloud-pubsublite/src/test/java/com/google/cloud/pubsublite/internal/wire/SubscriberImplTest.java
Messages queued in the serial executor should not be delivered post-seek.
=> fix: Flush messages in serial executor before handling admin seek

google-cloud-pubsublite/pom.xml
Declaring certain test-scope dependencies that are actually runtime dependencies.
Similar to https://github.com/googleapis/java-pubsub/issues/1239
=> fix: declaring test-scope artifact as runtime

google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/CloudRegionOrZone.java, google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/internal/wire/PublisherImpl.java
=> fix: improve performance of CloudRegionOrZone.parse and error message from PublisherImpl

.github/.OwlBot.lock.yaml, renovate.json
Reverts googleapis/java-pubsublite#1213
=> Revert "chore: pin versions of dependencies for compatibility with Python 3.6 (#1588)"

README.md, google-cloud-pubsublite/clirr-ignored-differences.xml, google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/AdminClient.java, google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/internal/AdminClientImpl.java, google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/internal/testing/UnitTestExamples.java, google-cloud-pubsublite/src/test/java/com/google/cloud/pubsublite/internal/AdminClientImplTest.java
Support creating subscriptions at a nominated target location within the message backlog. A seek is performed for publish and event timestamps.
Export subscriptions (pre-release feature) are also supported.
=> feat: Create subscriptions at a seek target

google-cloud-pubsublite/clirr-ignored-differences.xml, google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/internal/DefaultRoutingPolicy.java, google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/internal/RoutingPolicy.java, google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/internal/wire/PartitionCountWatchingPublisher.java, google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/internal/wire/RoutingPublisher.java, google-cloud-pubsublite/src/test/java/com/google/cloud/pubsublite/internal/DefaultRoutingPolicyTest.java, google-cloud-pubsublite/src/test/java/com/google/cloud/pubsublite/internal/wire/PartitionCountWatchingPublisherTest.java, google-cloud-pubsublite/src/test/java/com/google/cloud/pubsublite/internal/wire/RoutingPublisherTest.java
This is intended for use in the kafka connector, to send messages to the same pubsublite partition as they were published to in kafka
=> fix: Change RoutingPolicy to accept the whole message, not just the `key` field

README.md, google-cloud-pubsublite/clirr-ignored-differences.xml, google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/cloudpubsub/PublisherSettings.java, google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/internal/wire/ServiceClients.java
This is enabled by default and should save on network usage for clients
Internal reference b/269065916
=> feat: enable compression for publishing

google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/internal/AlarmFactory.java, google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/internal/wire/PublisherImpl.java, google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/internal/wire/SubscriberImpl.java
Do not process background requests in alarm pool while publish and subscribe streams are reconnecting. Avoid grabbing the same lock as reinitialize, which will be held until the stream is successfully reconnected.
Also reverts googleapis/java-pubsublite#1394, which can cause thread explosion.
=> fix: avoid blocking alarm pool during stream reconnects

google-cloud-pubsublite/pom.xml
This intends to fix issue in https://github.com/googleapis/java-cloud-bom/pull/6050#issuecomment-1610404487
dependency tree for `j2objc-annotations` without this fix:
```
[INFO] --------------< com.google.cloud:google-cloud-pubsublite >--------------
[INFO] Building Google Cloud Pub/Sub Lite 1.12.10-SNAPSHOT                [4/5]
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- maven-dependency-plugin:3.5.0:tree (default-cli) @ google-cloud-pubsublite ---
[INFO] com.google.cloud:google-cloud-pubsublite:jar:1.12.10-SNAPSHOT
[INFO] \- com.google.cloud:google-cloud-pubsub:jar:1.123.14:compile
[INFO]    \- com.google.j2objc:j2objc-annotations:jar:1.3:compile
```
- With out declaring version for `google-cloud-pubsub` here, it's getting …
=> deps: update dependency com.google.cloud:google-cloud-pubsub to v1.13.17. with temp fix.

README.md, google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/internal/wire/BatchPublisherImpl.java, google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/internal/wire/ConnectedAssignerImpl.java, google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/internal/wire/ConnectedCommitterImpl.java, google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/internal/wire/ConnectedSubscriberImpl.java, google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/internal/wire/SingleConnection.java, google-cloud-pubsublite/src/test/java/com/google/cloud/pubsublite/internal/wire/BatchPublisherImplTest.java, google-cloud-pubsublite/src/test/java/com/google/cloud/pubsublite/internal/wire/ConnectedCommitterImplTest.java, google-cloud-pubsublite/src/test/java/com/google/cloud/pubsublite/internal/wire/ConnectedSubscriberImplTest.java
This requires minimal changes and prevents thread explosion issues
=> fix: Change SingleConnection to batch before initial response instead of blocking

.kokoro/presubmit/graalvm-native-17.cfg, .kokoro/presubmit/graalvm-native.cfg, README.md, google-cloud-pubsublite-bom/pom.xml, owlbot.py, pom.xml
Notable Changes:
1) Use `gcr.io/cloud-devrel-public-resources/graalvm_sdk_platform*` docker images for Kokoro GraalVM tests  instead of `gcr.io/cloud-devrel-kokoro-resources/graalvm*`.
2) Use `com.google.cloud:sdk-platform-java-config` as the parent which inherits configs from `java-shared-config` and hosts the `google-cloud-shared-dependencies` version under the `google-cloud-shared-dependencies.version` property.  This artifact is versioned to be the same as google-cloud-shared-dependencies.
3) Adjust renovate-bot settings to update docker images when a new version of `sdk-platform-java-config` is on Maven Central in https://github.com/googleapis/java-pubsublite/pull/1585
Example renovate-bot update PR in google-cloud-java: https://github.com/googleapis/google-cloud-java/pull/10290
=> chore: use sdk-platform-java-config to consolidate build configs

.cloudbuild/samples_build.yaml, README.md
=> ci: sample build in Cloud Build

google-cloud-pubsublite/pom.xml, pom.xml
=> deps: Dont depend on google-cloud-bom. causes a circular dependency.

pom.xml
The google-cloud-pubsublite-bom is used in the libraries-bom: https://github.com/googleapis/java-cloud-bom/blob/2c49bcfe0a415e8255a7c9b3cc94951177a1da92/google-cloud-bom/pom.xml#L234 and causing the following failure in the shared-dependencies convergence check:
```
Found 1 artifacts with shared dependencies version: 3.37.0
Warning: cloud-pubsublite:1.14.4[WARNING] 
java.lang.RuntimeException: Failed to converge dependencies
at com.google.cloud.tools.opensource.cloudbomdashboard.DashboardMain.main (DashboardMain.java:114)
at org.codehaus.mojo.exec.ExecJavaMojo$1.run (ExecJavaMojo.java:254)
at java.lang.Thread.run (Thread.java:750)
```
This artifact seems to have been removed unintentionally in https://github.com/googleapis/java-pubsublite/pull/1748
=> fix: restore google-cloud-pubsublite-bom package

google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/Constants.java, google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/cloudpubsub/PublisherSettings.java, google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/internal/wire/ServiceClients.java, google-cloud-pubsublite/src/test/java/com/google/cloud/pubsublite/internal/wire/PublisherImplTest.java
This PR introduces `java.time` alternatives to existing `org.threeten.bp.*` methods, as well as switching internal variables (if any) to `java.time`
The main constraint is to keep the changes backwards compatible, so for each existing threeten method "`method1(org.threeten.bp.Duration)`" we will add an alternative with a _Duration_ (or _Timestamp_ when applicable) suffix: "`method1Duration(java.time.Duration)`".
For most cases, the implementation will be held in the `java.time` method and the old threeten method will just delegate the call to it. However, for the case of abstract classes, the implementation will be kept in the threeten method to avoid breaking changes (i.e. users that already overloaded the method in their user code).
=> feat: introduce `java.time` variables and methods

pom.xml
This disables errorprone checks for JDK 24 onwards.
The current version of errorprone is locked in order to confirm compatibility with JDK 11, but it's not compatible with JDk 24.
https://github.com/googleapis/java-pubsublite/blob/b9af4ce5597f40fc2e88f3b90b9ee3b4637a30f7/pom.xml#L73-L79
This PR drops errorprone when JDK >= 24 as a temporary workaround in order to get past the compilation stage and run the units against JDK 24+. The PubSub team will discuss a long term solution.
=> chore: disable errorprone for JDK 24 onwards

.github/scripts/update_generation_config.sh, .github/workflows/update_generation_config.yaml
Unfortunately, https://github.com/googleapis/sdk-platform-java/pull/3853 cannot be automatically propagated. 
This PR manually updates this script with the latest.
Confirmation in https://github.com/googleapis/java-pubsublite/actions/runs/16504875202
=> chore: manual update of update_generation_config.sh
